// Attested Board — seed records (source of truth).
//
// This is the canonical seed. The D1 migration (migrations/0002_seed_board.sql)
// is authored FROM this, and a gate test asserts every recordId here appears in
// that .sql — so the two cannot drift. Tests run the gates against this array
// directly (no live D1 in node:test); the deployed board serves the same rows
// from D1.
//
// Coverage is deliberate: every surface_shape (offered/auction_like/matching/
// stand) and every intent (wanted/offered/ask) appears at least once, so the
// acceptance gates have real rows to find. Themes continue examples.json; every
// domain is a `.example` placeholder. `ownerHandle` is a PRIVATE auth-shaped
// value (prefixed `auth:`) that must never appear in a public record — the
// no-leak gate searches projected output for exactly these strings.

import type { StoredBoardRow } from "./types.ts";

export const SEED_BOARD_RECORDS: StoredBoardRow[] = [
  {
    recordId: "rec-ito-notebook-edition",
    ownerHandle: "auth:ito-atelier-7f3a",
    ownerPublicRef: "Ito Atelier · ito-atelier.example",
    surfaceShape: "auction_like",
    intent: "offered",
    // No bare-"auction" category on the new board surface (N1 / hard-req §7);
    // surface_shape=auction_like already carries the shape.
    region: "Kyoto",
    title: "Hand-bound notebook set, edition of seven",
    summary: "Linen-thread binding on acid-free paper. Ships from Kyoto when bidding closes.",
    externalActionUrl: "https://ito-atelier.example/lots/notebook-seven",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-05-20T09:00:00Z",
  },
  {
    recordId: "rec-kellner-radio-1962",
    ownerHandle: "auth:kellner-9b21",
    ownerPublicRef: "Kellner Repair · kellner.example",
    surfaceShape: "auction_like",
    intent: "offered",
    // No bare-"auction" category on the new board surface (see above).
    title: "Restored 1962 tabletop radio",
    summary: "Chassis recapped, speaker reconditioned. In working order before it ships.",
    externalActionUrl: "https://kellner.example/lots/radio-1962",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-25T18:30:00Z",
    updatedAt: "2026-05-25T18:30:00Z",
  },
  {
    recordId: "rec-mariko-stoneware-mug",
    ownerHandle: "auth:mariko-kiln-4d10",
    ownerPublicRef: "Mariko Kiln · mariko.example",
    surfaceShape: "offered",
    intent: "offered",
    category: "sale",
    region: "Kyoto",
    title: "Wheel-thrown mug, stoneware",
    summary: "Thrown and glazed in small batches. Each one a little different.",
    externalActionUrl: "https://mariko.example/shop/stoneware-mug",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-23T10:45:00Z",
    updatedAt: "2026-05-23T10:45:00Z",
  },
  {
    recordId: "rec-hansei-calling-cards",
    ownerHandle: "auth:hansei-press-1c88",
    ownerPublicRef: "Hansei Press · hansei-press.example",
    surfaceShape: "offered",
    intent: "offered",
    category: "sale",
    title: "Letterpress calling cards, edition of fifty",
    summary: "Hand-set metal type, printed on cotton stock. Fifty cards to an edition.",
    externalActionUrl: "https://hansei-press.example/shop/calling-cards",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-22T14:00:00Z",
    updatedAt: "2026-05-22T14:00:00Z",
  },
  {
    recordId: "rec-hasegawa-knife-sharpening",
    ownerHandle: "auth:hasegawa-forge-6e52",
    ownerPublicRef: "Hasegawa Forge · hasegawa-forge.example",
    surfaceShape: "stand",
    intent: "offered",
    category: "service",
    title: "Knife sharpening by post",
    summary: "Send a blade; it comes back sharp. Turnaround about a week.",
    externalActionUrl: "https://hasegawa-forge.example/sharpening",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-15T13:00:00Z",
    updatedAt: "2026-05-15T13:00:00Z",
  },
  {
    recordId: "rec-quiet-tapes-shop",
    ownerHandle: "auth:quiet-tapes-2a47",
    ownerPublicRef: "Quiet Tapes · quiet-tapes.example",
    surfaceShape: "stand",
    intent: "offered",
    category: "music",
    title: "Quiet Tapes — standing catalogue",
    summary: "A small label's tapes and records, always open. New coastal recordings each season.",
    externalActionUrl: "https://quiet-tapes.example/catalogue",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-05T16:20:00Z",
    updatedAt: "2026-05-05T16:20:00Z",
  },
  {
    recordId: "rec-morning-draft-readers",
    ownerHandle: "auth:morning-draft-8f0c",
    ownerPublicRef: "Morning Draft · morning-draft.example",
    surfaceShape: "stand",
    intent: "ask",
    category: "writing",
    title: "Morning Draft — open call for reader notes",
    summary: "A weekly letter on revising in the open, asking readers what a week of notes should change.",
    externalActionUrl: "https://morning-draft.example/notes",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-18T05:00:00Z",
    updatedAt: "2026-05-18T05:00:00Z",
  },
  {
    recordId: "rec-hansei-press-operator",
    ownerHandle: "auth:hansei-press-1c88",
    ownerPublicRef: "Hansei Press · hansei-press.example",
    surfaceShape: "matching",
    intent: "wanted",
    category: "matching",
    region: "Kyoto",
    title: "Looking for a letterpress operator, two days a month",
    summary: "A small studio looking for someone who knows platen presses. Quiet work, regular hours.",
    externalActionUrl: "https://hansei-press.example/openings/operator",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-19T12:00:00Z",
    updatedAt: "2026-05-19T12:00:00Z",
  },
  {
    recordId: "rec-minato-darkroom-time",
    ownerHandle: "auth:minato-studio-3b9d",
    ownerPublicRef: "Minato Studio · minato-studio.example",
    surfaceShape: "matching",
    intent: "offered",
    category: "matching",
    region: "Kyoto",
    title: "Offering darkroom time, central Kyoto",
    summary: "A shared darkroom with two enlargers, open to careful hands on weekday evenings.",
    externalActionUrl: "https://minato-studio.example/darkroom",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-21T19:10:00Z",
    updatedAt: "2026-05-21T19:10:00Z",
  },
  {
    recordId: "rec-tidecraft-field-collab",
    ownerHandle: "auth:tidecraft-5c63",
    ownerPublicRef: "Tidecraft · tidecraft.example",
    surfaceShape: "matching",
    intent: "ask",
    category: "matching",
    title: "Coastal field-recording trade — who's nearby?",
    summary: "Asking other recordists on the coast whether anyone wants to swap a season of tapes.",
    externalActionUrl: "https://tidecraft.example/trade",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-10T11:00:00Z",
    updatedAt: "2026-05-10T11:00:00Z",
  },
];
