// Attested Board — seed records (source of truth).
//
// This is the canonical seed. The D1 migration (migrations/0002_seed_board.sql)
// is authored FROM this, and a gate test asserts every recordId here appears in
// that .sql — so the two cannot drift. Tests run the gates against this array
// directly (no live D1 in node:test); the deployed board serves the same rows
// from D1.
//
// Coverage is deliberate: every surface_shape (offered/auction_like/stand) and
// every intent (wanted/offered/ask) appears at least once, so the acceptance
// gates have real rows to find. The intent axis carries the "meeting" working
// that the removed matching surface used to hold — wanted rows (e.g. the
// letterpress-operator opening) meet offered/ask rows across stand/offered.
// Themes continue examples.json; every
// domain is a `.example` placeholder. `ownerHandle` is a PRIVATE auth-shaped
// value (prefixed `auth:`) that must never appear in a public record — the
// no-leak gate searches projected output for exactly these strings.

import type { StoredBoardRow } from "./types.ts";

export const SEED_BOARD_RECORDS: StoredBoardRow[] = [
  {
    recordId: "rec-ito-notebook-edition",
    ownerHandle: "auth:ito-atelier-7f3a",
    ownerPublicRef: "Ito Atelier · ito-atelier.example",
    surfaceShape: "auction_like",
    intent: "offered",
    // No bare-"auction" category on the new board surface (N1 / hard-req §7);
    // surface_shape=auction_like already carries the shape.
    region: "Kyoto",
    title: "Hand-bound notebook set, edition of seven",
    summary: "Linen-thread binding on acid-free paper. Ships from Kyoto when bidding closes.",
    externalActionUrl: "https://ito-atelier.example/lots/notebook-seven",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-05-20T09:00:00Z",
  },
  {
    recordId: "rec-kellner-radio-1962",
    ownerHandle: "auth:kellner-9b21",
    ownerPublicRef: "Kellner Repair · kellner.example",
    surfaceShape: "auction_like",
    intent: "offered",
    // No bare-"auction" category on the new board surface (see above).
    title: "Restored 1962 tabletop radio",
    summary: "Chassis recapped, speaker reconditioned. In working order before it ships.",
    externalActionUrl: "https://kellner.example/lots/radio-1962",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-25T18:30:00Z",
    updatedAt: "2026-05-25T18:30:00Z",
  },
  {
    recordId: "rec-mariko-stoneware-mug",
    ownerHandle: "auth:mariko-kiln-4d10",
    ownerPublicRef: "Mariko Kiln · mariko.example",
    surfaceShape: "offered",
    intent: "offered",
    category: "sale",
    region: "Kyoto",
    title: "Wheel-thrown mug, stoneware",
    summary: "Thrown and glazed in small batches. Each one a little different.",
    externalActionUrl: "https://mariko.example/shop/stoneware-mug",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-23T10:45:00Z",
    updatedAt: "2026-05-23T10:45:00Z",
  },
  {
    recordId: "rec-hansei-calling-cards",
    ownerHandle: "auth:hansei-press-1c88",
    ownerPublicRef: "Hansei Press · hansei-press.example",
    surfaceShape: "offered",
    intent: "offered",
    category: "sale",
    title: "Letterpress calling cards, edition of fifty",
    summary: "Hand-set metal type, printed on cotton stock. Fifty cards to an edition.",
    externalActionUrl: "https://hansei-press.example/shop/calling-cards",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-22T14:00:00Z",
    updatedAt: "2026-05-22T14:00:00Z",
  },
  {
    recordId: "rec-hasegawa-knife-sharpening",
    ownerHandle: "auth:hasegawa-forge-6e52",
    ownerPublicRef: "Hasegawa Forge · hasegawa-forge.example",
    surfaceShape: "stand",
    intent: "offered",
    category: "service",
    title: "Knife sharpening by post",
    summary: "Send a blade; it comes back sharp. Turnaround about a week.",
    externalActionUrl: "https://hasegawa-forge.example/sharpening",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-15T13:00:00Z",
    updatedAt: "2026-05-15T13:00:00Z",
  },
  {
    recordId: "rec-quiet-tapes-shop",
    ownerHandle: "auth:quiet-tapes-2a47",
    ownerPublicRef: "Quiet Tapes · quiet-tapes.example",
    surfaceShape: "stand",
    intent: "offered",
    category: "music",
    title: "Quiet Tapes — standing catalogue",
    summary: "A small label's tapes and records, always open. New coastal recordings each season.",
    externalActionUrl: "https://quiet-tapes.example/catalogue",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-05T16:20:00Z",
    updatedAt: "2026-05-05T16:20:00Z",
  },
  {
    recordId: "rec-morning-draft-readers",
    ownerHandle: "auth:morning-draft-8f0c",
    ownerPublicRef: "Morning Draft · morning-draft.example",
    surfaceShape: "stand",
    intent: "ask",
    category: "writing",
    title: "Morning Draft — open call for reader notes",
    summary: "A weekly letter on revising in the open, asking readers what a week of notes should change.",
    externalActionUrl: "https://morning-draft.example/notes",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-18T05:00:00Z",
    updatedAt: "2026-05-18T05:00:00Z",
  },
  {
    recordId: "rec-hansei-press-operator",
    ownerHandle: "auth:hansei-press-1c88",
    ownerPublicRef: "Hansei Press · hansei-press.example",
    // Canonical narrowing: matching+wanted → stand+wanted (§3 default). category
    // "matching" dropped — the board carries no matching surface/label.
    surfaceShape: "stand",
    intent: "wanted",
    region: "Kyoto",
    title: "Looking for a letterpress operator, two days a month",
    summary: "A small studio looking for someone who knows platen presses. Quiet work, regular hours.",
    externalActionUrl: "https://hansei-press.example/openings/operator",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-19T12:00:00Z",
    updatedAt: "2026-05-19T12:00:00Z",
  },
  {
    recordId: "rec-minato-darkroom-time",
    ownerHandle: "auth:minato-studio-3b9d",
    ownerPublicRef: "Minato Studio · minato-studio.example",
    // matching+offered → stand+offered (§3 default — a standing availability).
    surfaceShape: "stand",
    intent: "offered",
    region: "Kyoto",
    title: "Offering darkroom time, central Kyoto",
    summary: "A shared darkroom with two enlargers, open to careful hands on weekday evenings.",
    externalActionUrl: "https://minato-studio.example/darkroom",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-21T19:10:00Z",
    updatedAt: "2026-05-21T19:10:00Z",
  },
  {
    recordId: "rec-tidecraft-field-collab",
    ownerHandle: "auth:tidecraft-5c63",
    ownerPublicRef: "Tidecraft · tidecraft.example",
    // matching+ask → stand+ask (§3 default).
    surfaceShape: "stand",
    intent: "ask",
    title: "Coastal field-recording trade — who's nearby?",
    summary: "Asking other recordists on the coast whether anyone wants to swap a season of tapes.",
    externalActionUrl: "https://tidecraft.example/trade",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-10T11:00:00Z",
    updatedAt: "2026-05-10T11:00:00Z",
  },

  // ── Launch demo seed (#5) — 5 beta boards, cold-start起点 ─────────────────────────
  //
  // ★ These are a LAUNCH DEMO SEED (C1 = (b)): owner-owned-in-principle illustrative
  // boards, NOT real consented beta-owner boards. Same demo convention as the rows
  // above — `.example` domains and synthetic `auth:` handles — so nothing here claims
  // a real person's identity or contact. They demonstrate the EXISTING stages (they
  // pass their own gates): each board is a group of canonical rows (Board Templates'
  // grouping) that meets the minimum public criteria (a title, ≥1 row, a Contact-Kit-
  // compatible action). There is NO fabricated activity — evidence/receipt refs are
  // empty, and no copy implies a sale, a receipt, popularity, or a completed deal.
  // PX curates nothing: the order is registration order, and no row is featured.
  // (At 発表, real consented boards replace these — a deploy-stage standing item.)

  // 1 — bonsai (Aoi Bonsai)
  {
    recordId: "rec-aoi-bonsai-piece",
    ownerHandle: "auth:aoi-bonsai-3f21",
    ownerPublicRef: "Aoi Bonsai · aoi-bonsai.example",
    surfaceShape: "auction_like",
    intent: "offered",
    region: "Kyoto",
    title: "一点物の黒松、入札で譲ります",
    summary: "一点ものの黒松。入札を受け付けています。",
    externalActionUrl: "https://aoi-bonsai.example/lots/black-pine",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-24T09:00:00Z",
    updatedAt: "2026-05-24T09:00:00Z",
  },
  {
    recordId: "rec-aoi-bonsai-care-ask",
    ownerHandle: "auth:aoi-bonsai-3f21",
    ownerPublicRef: "Aoi Bonsai · aoi-bonsai.example",
    surfaceShape: "stand",
    intent: "ask",
    title: "盆栽の手入れ相談、受けています",
    summary: "植え替えや剪定の相談を受けています。",
    externalActionUrl: "https://aoi-bonsai.example/care",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-16T10:00:00Z",
    updatedAt: "2026-05-16T10:00:00Z",
  },
  {
    // 1-to-many: a standing gathering (a monthly care meetup looking for hands).
    recordId: "rec-aoi-bonsai-care-meet",
    ownerHandle: "auth:aoi-bonsai-3f21",
    ownerPublicRef: "Aoi Bonsai · aoi-bonsai.example",
    surfaceShape: "stand",
    intent: "wanted",
    region: "Kyoto",
    title: "月一の手入れ会、一緒にやる方を探しています",
    summary: "月に一度の手入れ会。一緒に手を動かす方を探しています。",
    externalActionUrl: "https://aoi-bonsai.example/meetup",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-12T11:00:00Z",
    updatedAt: "2026-05-12T11:00:00Z",
  },

  // 2 — designer (Midori Design)
  {
    recordId: "rec-midori-logo",
    ownerHandle: "auth:midori-design-7a4c",
    ownerPublicRef: "Midori Design · midori-design.example",
    surfaceShape: "offered",
    intent: "offered",
    title: "ロゴ制作を受けています",
    summary: "小さなお店やプロジェクトのロゴをつくっています。",
    externalActionUrl: "https://midori-design.example/logo",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-26T09:30:00Z",
    updatedAt: "2026-05-26T09:30:00Z",
  },
  {
    // A wanted row — cross-intent fodder against the offered boards.
    recordId: "rec-midori-commission-wanted",
    ownerHandle: "auth:midori-design-7a4c",
    ownerPublicRef: "Midori Design · midori-design.example",
    surfaceShape: "offered",
    intent: "wanted",
    title: "限定の制作で組める方を探しています",
    summary: "期間限定の制作で一緒に動けるイラストレーターを探しています。",
    externalActionUrl: "https://midori-design.example/collab",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-17T13:00:00Z",
    updatedAt: "2026-05-17T13:00:00Z",
  },
  {
    recordId: "rec-midori-goods",
    ownerHandle: "auth:midori-design-7a4c",
    ownerPublicRef: "Midori Design · midori-design.example",
    surfaceShape: "offered",
    intent: "offered",
    region: "Osaka",
    title: "オリジナル小物を販売しています",
    summary: "ステッカーや栞などの小物を不定期に販売しています。",
    externalActionUrl: "https://midori-design.example/goods",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-11T15:00:00Z",
    updatedAt: "2026-05-11T15:00:00Z",
  },

  // 3 — 3D printer (Hina Fabrication)
  {
    recordId: "rec-hina-parts",
    ownerHandle: "auth:hina-fab-9c12",
    ownerPublicRef: "Hina Fabrication · hina-fab.example",
    surfaceShape: "offered",
    intent: "offered",
    title: "部品の制作・出力を受けています",
    summary: "STLからの出力や試作の部品制作を受けています。",
    externalActionUrl: "https://hina-fab.example/print",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-27T09:00:00Z",
    updatedAt: "2026-05-27T09:00:00Z",
  },
  {
    recordId: "rec-hina-modelfix-wanted",
    ownerHandle: "auth:hina-fab-9c12",
    ownerPublicRef: "Hina Fabrication · hina-fab.example",
    surfaceShape: "offered",
    intent: "wanted",
    title: "モデル修正を手伝える方を探しています",
    summary: "出力前のモデル修正を手伝ってくれる方を探しています。",
    externalActionUrl: "https://hina-fab.example/modelfix",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-14T13:00:00Z",
    updatedAt: "2026-05-14T13:00:00Z",
  },
  {
    // 1-to-many: a standing open call (a print clinic anyone can ask into).
    recordId: "rec-hina-print-clinic",
    ownerHandle: "auth:hina-fab-9c12",
    ownerPublicRef: "Hina Fabrication · hina-fab.example",
    surfaceShape: "stand",
    intent: "ask",
    title: "出力の相談会、随時ひらいています",
    summary: "素材や設定の相談会を随時ひらいています。",
    externalActionUrl: "https://hina-fab.example/clinic",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-09T10:30:00Z",
    updatedAt: "2026-05-09T10:30:00Z",
  },

  // 4 — SE musician (Nagi Sound)
  {
    recordId: "rec-nagi-se",
    ownerHandle: "auth:nagi-sound-2b88",
    ownerPublicRef: "Nagi Sound · nagi-sound.example",
    surfaceShape: "offered",
    intent: "offered",
    title: "効果音の制作を受けています",
    summary: "ゲームや映像向けの効果音を制作しています。",
    externalActionUrl: "https://nagi-sound.example/se",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-28T09:00:00Z",
    updatedAt: "2026-05-28T09:00:00Z",
  },
  {
    recordId: "rec-nagi-soundpack",
    ownerHandle: "auth:nagi-sound-2b88",
    ownerPublicRef: "Nagi Sound · nagi-sound.example",
    surfaceShape: "offered",
    intent: "offered",
    title: "音素材を配布・販売しています",
    summary: "環境音や効果音の素材をまとめて配布・販売しています。",
    externalActionUrl: "https://nagi-sound.example/packs",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-13T14:30:00Z",
    updatedAt: "2026-05-13T14:30:00Z",
  },
  {
    // 1-to-many: a standing recruit for collaborators (game-making mates).
    recordId: "rec-nagi-gamemates",
    ownerHandle: "auth:nagi-sound-2b88",
    ownerPublicRef: "Nagi Sound · nagi-sound.example",
    surfaceShape: "stand",
    intent: "wanted",
    title: "一緒にゲームを作る仲間を募集しています",
    summary: "個人制作のゲームで音まわりを一緒にやる仲間を募集しています。",
    externalActionUrl: "https://nagi-sound.example/team",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-08T08:00:00Z",
    updatedAt: "2026-05-08T08:00:00Z",
  },

  // 5 — restaurant (Komorebi Kitchen)
  {
    recordId: "rec-komorebi-event",
    ownerHandle: "auth:komorebi-6d55",
    ownerPublicRef: "Komorebi Kitchen · komorebi-kitchen.example",
    surfaceShape: "stand",
    intent: "offered",
    region: "Kobe",
    title: "週末の間借りイベント、やっています",
    summary: "週末だけの間借りキッチン。月替わりの料理を出しています。",
    externalActionUrl: "https://komorebi-kitchen.example/events",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-29T17:00:00Z",
    updatedAt: "2026-05-29T17:00:00Z",
  },
  {
    recordId: "rec-komorebi-menu",
    ownerHandle: "auth:komorebi-6d55",
    ownerPublicRef: "Komorebi Kitchen · komorebi-kitchen.example",
    surfaceShape: "offered",
    intent: "offered",
    title: "季節の限定メニューを出しています",
    summary: "季節の食材で限定メニューを不定期に出しています。",
    externalActionUrl: "https://komorebi-kitchen.example/menu",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-15T12:00:00Z",
    updatedAt: "2026-05-15T12:00:00Z",
  },
  {
    // 1-to-many: a standing recruit for weekend help.
    recordId: "rec-komorebi-staff-wanted",
    ownerHandle: "auth:komorebi-6d55",
    ownerPublicRef: "Komorebi Kitchen · komorebi-kitchen.example",
    surfaceShape: "stand",
    intent: "wanted",
    region: "Kobe",
    title: "週末の手伝いスタッフを募集しています",
    summary: "週末の数時間、ホールを手伝ってくれる方を募集しています。",
    externalActionUrl: "https://komorebi-kitchen.example/staff",
    evidenceRefs: [],
    receiptRefs: [],
    createdAt: "2026-05-07T16:00:00Z",
    updatedAt: "2026-05-07T16:00:00Z",
  },
];
